### PR TITLE
add target _blank to links

### PR DESCRIPTION
**Pull request by kand**
Adds `target="_blank"` to inline links.

**Release Type**: _patch_
Only a small update, no breaking changes.

**New**

1. Inline links get `target="_blank"`.

### CODE REVIEW

**Comment by kand** [comment]
[Update content links](https://trello.com/c/wsrtzvBI/118-update-content-links)

**Review by spra85 — APPROVED** [review]

**Comment by shawncook** [comment]
Nice 👍

**Comment by collin** [comment]
This will happen to all link all the time?

**Comment by kand** [comment]
Yea, double checked this is what we want going forward and the answer was yes.

**Comment by collin** [comment]
Cool :+1:

**Pull request merged**
